// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf64tFxCc2cx9YD_xr22D-S9e9CXpd2g4',
    appId: '1:858739015011:web:b22c915b7bdd95c6072756',
    messagingSenderId: '858739015011',
    projectId: 'pata-f9bae',
    authDomain: 'pata-f9bae.firebaseapp.com',
    storageBucket: 'pata-f9bae.appspot.com',
    measurementId: 'G-Q06GRFX8CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTyzLf6W8kSHKaWwBAflQU9-Gtwe1P63s',
    appId: '1:858739015011:android:383f71e6506eab64072756',
    messagingSenderId: '858739015011',
    projectId: 'pata-f9bae',
    storageBucket: 'pata-f9bae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYfhYRz20clp_50yZ01ipl0ZVBl5hfqRQ',
    appId: '1:858739015011:ios:55d52c9aed1d1bee072756',
    messagingSenderId: '858739015011',
    projectId: 'pata-f9bae',
    storageBucket: 'pata-f9bae.appspot.com',
    iosClientId: '858739015011-qq7n2d05ifdssdnfujkr6li22lcv8pss.apps.googleusercontent.com',
    iosBundleId: 'com.example.pata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYfhYRz20clp_50yZ01ipl0ZVBl5hfqRQ',
    appId: '1:858739015011:ios:55d52c9aed1d1bee072756',
    messagingSenderId: '858739015011',
    projectId: 'pata-f9bae',
    storageBucket: 'pata-f9bae.appspot.com',
    iosClientId: '858739015011-qq7n2d05ifdssdnfujkr6li22lcv8pss.apps.googleusercontent.com',
    iosBundleId: 'com.example.pata',
  );
}
